### ISSUE TITLE
Console access?

### ISSUE THREAD

**Issue by JoshTheBlack** [flobernd/docker-minecraft-ftb#1]
Is there any way to access a console to enter commands?

**Comment by flobernd** [comment]
Hi @JoshTheBlack

Yes! If you followed the example from the README, the container runs in interactive terminal mode (-it).

You can e.g. use the following command to attach to the container to see console output and as well enter console commands:

docker attach "minecraft-ftb"

Replace the quoted name with the name of your Minecraft container, in case you changed it.

**Comment by JoshTheBlack** [comment]
Thanks!
